LDAP:
  url: 'ldaps://people.unige.ch:636'
  bindDN: 'cn=HPC search agent,ou=HPC,ou=Applications,dc=unige,dc=ch'
  bindCredentials: 'xxxxxxx'
  rootCA: 'root-cert09.pem' 
web:
  urlRoot: 'https://baobabmaster.unige.ch/iface-dev/'
  port: 6000 

